name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # Matches tags starting with "v"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version you're using

    - name: Restore dependencies
      run: dotnet restore ./src/Mockiu/Mockiu/Mockiu.csproj  # Specify the path to your .csproj file

    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/Mockiu/Mockiu/Mockiu.csproj  # Specify the path to your .csproj file

    - name: Pack
      run: dotnet pack --configuration Release --no-restore --output ./nupkg ./src/Mockiu/Mockiu/Mockiu.csproj  # Specify the path to your .csproj file

    - name: Publish NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json